name: Deploy Form app
on:
  push:
    branches:
      - preprod
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Project initialization
        uses: actions/checkout@v2
      - name: Typescript Linter
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          pattern: '*.ts'
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
      - name: Deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP_PREPROD}}
